const fs = require("fs");
const path = "src/hooks/useAnalyticsData.ts";
const lines = fs.readFileSync(path, "utf8").split(/\r?\n/);
lines.splice(529, 0,
  "",
  "function extractHostname(value?: string | null) {",
  "  if (!value) return ';",
  "  try {",
  "    return new URL(value).hostname.replace(/^www\\./, ').toLowerCase();",
  "  } catch {",
  "    return value.replace(/^https?:\\/\\//, ').replace(/^www\\./, ').split(/[\\/?#]/)[0]?.toLowerCase() || ';",
  "  }",
  "}",
  "",
  "function prettySourceLabel(value: string) {",
  "  return value",
  "    .replace(/^www\\./, ')",
  "    .replace(/[-_]+/g, ' ')",
  "    .replace(/\\s+/g, ' ')",
  "    .trim()",
  "    .replace(/\\b\\w/g, (char) => char.toUpperCase());",
  "}",
  "",
  "function normalizeSourceLabel(job: any) {",
  "  const rawSource = typeof job?.source_type === 'string' ? job.source_type.trim() : ';",
  "  const fromUrl =",
  "    extractHostname(job?.apply_url) ||",
  "    extractHostname(job?.raw_data?.apply_url) ||",
  "    extractHostname(job?.raw_data?.job_url) ||",
  "    extractHostname(job?.raw_data?.source_url) ||",
  "    extractHostname(job?.raw_data?.url);",
  "  if (rawSource && rawSource.includes('.')) return rawSource.toLowerCase();",
  "  if (fromUrl) return fromUrl;",
  "  if (rawSource) return prettySourceLabel(rawSource);",
  "  return 'Unknown';",
  "}",
  "",
  "function indexedColor(index: number) {",
  "  const palette = ['#ffd700', '#56c2ff', '#f59e0b', '#fb7185', '#a78bfa', '#14b8a6'];",
  "  return palette[index % palette.length];",
  "}",
);
lines.splice(425, 1, "  return { chartDataApps, chartDataJobs, barData, sourceBreakdown, donutData, matchBarData, metrics, comparisons, loading, error, lastUpdated, refresh, exportCSV, exportJSON, snapshot } as const;");
lines.splice(384, 9,
  "      writeCache(cacheKey, {",
  "        chartDataApps: appsSeries,",
  "        chartDataJobs: jobsSeries,",
  "        barData: bar,",
  "        sourceBreakdown: sourceBreakdownData,",
  "        donutData: donut,",
  "        matchBarData: matchBar,",
  "        metrics: nextMetrics,",
  "        comparisons: nextComparisons,",
  "        lastUpdated: Date.now(),",
  "      });",
);
lines.splice(379, 0, "      setSourceBreakdown(sourceBreakdownData);");
lines.splice(335, 7,
  "      const statusCounts = groupCounts(apps.map((a: any) => a.status || 'Unknown'));",
  "      const totalStatus = Array.from(statusCounts.values()).reduce((sum, count) => sum + count, 0) || 1;",
  "      const donut = Array.from(statusCounts.entries())",
  "        .sort((a, b) => b[1] - a[1])",
  "        .map(([name, count]) => ({",
  "          name,",
  "          value: count,",
  "          share: Math.round((count / totalStatus) * 100),",
  "          color: pickColor(name),",
  "        }));",
);
lines.splice(239, 9,
  "      const sourceCounts = groupCounts(jobs.map((job: any) => normalizeSourceLabel(job)));",
  "      const sourceBreakdownData = Array.from(sourceCounts.entries())",
  "        .filter(([name]) => Boolean(name))",
  "        .sort((a, b) => b[1] - a[1])",
  "        .slice(0, 6)",
  "        .map(([name, value], index) => ({",
  "          name,",
  "          value,",
  "          color: indexedColor(index),",
  "        }));",
  "      const sources = sourceCounts.size;",
);
lines[213] = "        .select(\"id, created_at, source_type, apply_url, user_id, title, company, raw_data\")";
lines[204] = "        .select(\"id, applied_date, created_at, status, updated_at, user_id, match_score, notes\")";
lines.splice(193, 0, "          setSourceBreakdown(cached.sourceBreakdown || []);");
lines.splice(176, 0, "        setSourceBreakdown([]);");
lines.splice(137, 4,
  "    barData,",
  "    sourceBreakdown,",
  "    donutData,",
  "    matchBarData,",
  "    error,",
);
lines.splice(92, 8,
  "      rows.push(\"\");",
  "      push([\"Source\",\"Count\",\"Color\"]);",
  "      for (const source of sourceBreakdown) push([source.name, source.value, source.color]);",
  "      rows.push(\"\");",
  "      push([\"Status\",\"Count\",\"Share %\",\"Color\"]);",
  "      for (const d of donutData) push([d.name, d.value, d.share ?? 0, d.color]);",
  "",
  "      if (matchBarData.length) {",
);
lines.splice(16, 0, "  const [sourceBreakdown, setSourceBreakdown] = useState<{ name: string; value: number; color: string }[]>([]);");
fs.writeFileSync(path, lines.join("\n"));
